### ISSUE TITLE
Blueshift’s service files in the Documents directory

### ISSUE THREAD

**Issue by stormgain-dev** [blueshift-labs/Blueshift-Cordova-Plugin#25]
Hello,

In our iOS app, we want the users to be able to download files and store/manage them in the app’s Documents directory. We made the Documents directory visible in the iOS’s “Files” app by setting both `UIFileSharingEnabled` and `LSSupportsOpeningDocumentsInPlace` to `<true/>` in the Info.plist file. Everything is OK, but one embarrassing thing is a set of internal-use service files created by the Blueshift SDK in the Documents directory. They are also visible to the users which is not so good.

![blueshift](https://user-images.githubusercontent.com/84320632/126282221-c467390b-ed20-43cd-ac13-f05689fa4088.png)

Is there a way to hide these service files? If it’s not possible to make these files invisible to the users, maybe at least collect them in a single namespace-like subdirectory containing everything required by the Blueshift SDK?

Thanks in advance

**Comment by stormgain-dev** [comment]
The problem would be (kinda) solved if these files were renamed to start with a period “.” (or if they were placed in a subdirectory having such a name starting with the period character). This [would make files](https://noteswriter.zendesk.com/hc/en-us/articles/360009029258-How-to-hide-files-or-folders-from-the-Files-iOS-app-) at least visually hidden which is far better than what we have now.

Could this change be implemented in the Blueshift SDK, or probably could the problem be fixed in some other way?

**Comment by ketanshikharebsft** [comment]
@stormgain-dev We have released the Cordova plugin [v0.0.3](https://github.com/blueshift-labs/Blueshift-Cordova-Plugin/releases/tag/0.0.3) which has a fix for this issue. Please refer to the [documentation](https://developer.blueshift.com/docs/blueshifts-cordova-plugin#ios-1) for more details.
